/* 
* Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license 
* Click nbfs://nbhost/SystemFileSystem/Templates/Classes/Main.java to edit this template 
*/ 

/** 

* class name:  SnarkPack.java  
* @amelia maxwell 
*  x23471092 

*/ 

package settings; 

import settings.ShakespearePack; 
import settings.PiratePack; 
import settings.Wizardpack; 

  
public class SnarkPack{ 
    private String style; 
    private String level; 
    private String username; 
    private String theme;         // color theme ie dark or light 

 
    public SnarkPack() { //constructer for when app first runs ie no setting chosen 
        style = ""; 
        level = ""; 
        username = ""; 
        theme = ""; 
    } 
    

//overloaded con so no sets 
    public SnarkPack(String style, String level, String username, String theme) { 
        this.style = style; 
        this.level = level; 
        this.username = username; 
        this.theme = theme; 
    } 


    //getters 
         public String getStyle(){  
             return style;  
         } 
        public String getLevel(){  
            return level;  
        } 

        public String getUsername(){  
            return username;  
        } 
         
        public String getTheme(){ 
            return theme;  
        } 
  

    // gets praise based on styel and level 
             public String getPraise() { 
                    if (level.equalsIgnoreCase("Off")) {///combo boses for this option are in string added ignore case to avoid any issues 
                        return "";//returns npothing if user has it off 

                    }if (style.equals("Pirate")) { 
                          PiratePack p = new PiratePack(username);//this makes an instance of pirate pack so now p has all the pirates snark logic 
                        return p.getPraise(level);//gets the pirate style praise message with the right level 
                    } 
                    if (style.equals("Shakespearean")) { 
                         ShakespearePack s = new ShakespearePack(username); 
                        return s.getPraise(level); 
                    } 
                    if (style.equals("Wizard")) { 
                        Wizardpack w = new Wizardpack(username); 
                        return w.getPraise(level); 
                    } 
                 //needs a return statement 
                    return "Try again, " + username + "."; 
                } 
                /////////////////////////////////////////////////////////////////////////////////////////////////////////////////// 

                 

//gets scold using the same logic as the getPraise method 
            public String getScold() { 
            if (level.equalsIgnoreCase("Off")) { 
                return ""; 
            } 
            if (style.equals("Pirate")) { 
                          PiratePack p = new PiratePack(username); 
                        return p.getScold(level); 
                    } 
            if (style.equals("Shakespearean")) { 
                         ShakespearePack s = new ShakespearePack(username); 
                        return s.getScold(level); 
            } 
            if (style.equals("Wizard")) { 
                        Wizardpack w = new Wizardpack(username); 
                        return w.getScold(level); 
            } 
             return "Try again, " + username + "."; 
            }  
           /////////////////////////////////////////////////////////////////////////////////////////////////////////////// 

            public String getEncouragement() { 
             if (level.equalsIgnoreCase("Off")) { 
                return ""; 
            } 

            if (style.equals("Pirate")) { 
                          PiratePack p = new PiratePack(username); 
                        return p.getEncouragement(level); 
                    } 
            if (style.equals("Shakespearean")) { 
                         ShakespearePack s = new ShakespearePack(username); 
                        return s.getEncouragement(level); 
            } 
            if (style.equals("Wizard")) { 
                        Wizardpack w = new Wizardpack(username); 
                        return w.getEncouragement(level); 
            } 
             return "Try again, " + username + "."; 
            }  
/////////////////////////////////////////////////////////////////
  

    void setTheme(String chosenTheme) {//autogenerated 
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody 

    } 

  

    

} 

  

  

  

/* 

The purpose of this file is to remember the users settings like snark levl, style, and name 

it uses polymorphismm to get the right snark pack when programme runs  

and encapsulation to keep the users preferences in one object  

the strateddy pattern basically lets each style have their own class with its own messages and behaviour 

*/ 