package Task;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/Classes/Main.java to edit this template
 */

/**
 * class name: TaskPanel.java
 * @Ciara Lynch
 *  x23461962
 * this class is to create tasks with all their attributes, edit, delete and update them too, 
 *          while displaying them into a table format with a separate list for sub tasks
 */

import stt.landingPage;
import Task.storage.taskRepository;
import Task.storage.fileTaskRepository;
import javax.swing.JOptionPane;
import settings.SnarkPack;
import settings.snarkUI;
import settings.ThemeManager;


public class taskPanel extends javax.swing.JFrame {
    // this lets us have a memory of tasks in an array list
    private final java.util.List<Task> taskList = new java.util.ArrayList<>();
    // this is our table
    private javax.swing.table.DefaultTableModel taskTableModel;
    // thsi is the subtask list
    private javax.swing.DefaultListModel<String> burdenListModel;
    // simple auto id for tasks
    private int nextId = 1;
    // index of task currently being edited its -1 cause were are updating ie slecting a task not creating another
    private int editingIndex = -1;
    //gets to file where tasks are mamaged 
     private taskRepository repo; 
     //wheres fles are stired on disks ie stored to tasks.dat in sst file
     private static final String filePath= "tasks.dat";
     //snark pack from settings
     private SnarkPack snarkPack;


    /*
    constructer
    */
    public taskPanel() {
        initComponents(); //this gets all the pieces like buttons and labels from netbeans

        // connect our table to a default model so we can add delete etc operations 
        taskTableModel = (javax.swing.table.DefaultTableModel) burdentable.getModel();
        taskTableModel.setRowCount(0); // clears rows
        
        
        
        //connects our list to the default model 
        burdenListModel = new javax.swing.DefaultListModel<>();
        burdenlist.setModel(burdenListModel);


        // grab whatever the user picked in sETTINGS
       snarkPack = snarkUI.currentSnarkPack;
        ThemeManager.applyTheme(this, snarkPack);
        
        // fill priority combo from enum
        priority.removeAllItems();
        
        for (Priority p : Priority.values()) {
            priority.addItem(p.name());   // shows enum names
        }

        // fill category combo from enum
        category.removeAllItems(); //clears anything in the box so we can start fresh
        
        for (Category c : Category.values()) {
            category.addItem(c.name());
        }
        
        //sets up file repsoitory 
      repo = new fileTaskRepository(filePath);
    taskList.clear();
    taskList.addAll(repo.findAll());//loads existing tasks from file
    refreshTable();
    int maxId = 0;
    for (Task t : taskList) {
        if (t.getId() > maxId) {
            maxId = t.getId();    // make sure nextId continues on higher from the highest existing task id
        }
    }
            nextId = maxId + 1;
    }

    // a constructor for snark 
    public taskPanel(SnarkPack snarkPack) {
        this();                 //this calls our default constrcutorconstructor without it our GUI would  break cuz our tables, lists wouldnt be set up, our tasks souldnt load from file, and it runs our init componenst 
        this.snarkPack = snarkPack;  // store the chosen snark settings
    }

        private void applyThemeFromSnark() {
        if (snarkPack == null) return;
        String theme = snarkPack.getTheme();
        // same logic as before
    }


    // this is how we add new rows ie tasks to the table
    private void addTaskToTable(Task t) {
        taskTableModel.addRow(new Object[]{
            t.getTitle(),
           t.checkOverdue(),
            t.getPriority(),
            t.getCategory(),
            t.getStatus()
        });
    }

    // this is used when a user edits a task so its changes appear on the table
    private void refreshTable() {
        taskTableModel.setRowCount(0);
        for (Task t : taskList) {
            addTaskToTable(t);
        }
    }
    
    //this takes the sub tasks titles and adds it to our list
      private void showSubtasks(Task t) {
            burdenListModel.clear();
            if (t == null) return;
            for (SubTask st : t.getSubTasks()) {
                burdenListModel.addElement(st.getTitle());
    }
}


    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane3 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        homebutton = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        title = new javax.swing.JTextField();
        priority = new javax.swing.JComboBox<>();
        category = new javax.swing.JComboBox<>();
        jLabel7 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        subtask = new javax.swing.JTextPane();
        jScrollPane2 = new javax.swing.JScrollPane();
        burdenlist = new javax.swing.JList<>();
        jLabel8 = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        burdentable = new javax.swing.JTable();
        markdone = new javax.swing.JButton();
        deletebutton = new javax.swing.JButton();
        editbutton = new javax.swing.JButton();
        undonebutton = new javax.swing.JButton();
        createburden = new javax.swing.JButton();
        duedate = new javax.swing.JTextField();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane3.setViewportView(jTable1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Modern No. 20", 0, 36)); // NOI18N
        jLabel1.setText("Scroll of Burdens");

        homebutton.setFont(new java.awt.Font("Modern No. 20", 0, 18)); // NOI18N
        homebutton.setText("GO HOME");
        homebutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                homebuttonActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Palatino Linotype", 3, 14)); // NOI18N
        jLabel2.setText("Create Burden");

        jLabel3.setFont(new java.awt.Font("Palatino Linotype", 0, 12)); // NOI18N
        jLabel3.setText("Title");

        jLabel4.setFont(new java.awt.Font("Palatino Linotype", 0, 12)); // NOI18N
        jLabel4.setText("Due Date");

        jLabel5.setFont(new java.awt.Font("Palatino Linotype", 0, 12)); // NOI18N
        jLabel5.setText("Priority");

        jLabel6.setFont(new java.awt.Font("Palatino Linotype", 0, 12)); // NOI18N
        jLabel6.setText("Category");

        title.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                titleActionPerformed(evt);
            }
        });

        priority.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        category.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel7.setFont(new java.awt.Font("Palatino Linotype", 0, 12)); // NOI18N
        jLabel7.setText("Sub Task");

        jScrollPane1.setViewportView(subtask);

        burdenlist.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        burdenlist.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                burdenlistMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(burdenlist);

        jLabel8.setFont(new java.awt.Font("Palatino Linotype", 3, 14)); // NOI18N
        jLabel8.setText("Burdens Subtasks");

        burdentable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, "", null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Title", "Due Date", "Priority", "Category", "Status"
            }
        ));
        jScrollPane4.setViewportView(burdentable);

        markdone.setFont(new java.awt.Font("Modern No. 20", 1, 14)); // NOI18N
        markdone.setText("Mark Done");
        markdone.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                markdoneActionPerformed(evt);
            }
        });

        deletebutton.setFont(new java.awt.Font("Modern No. 20", 1, 14)); // NOI18N
        deletebutton.setText("Delete");
        deletebutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deletebuttonActionPerformed(evt);
            }
        });

        editbutton.setFont(new java.awt.Font("Modern No. 20", 1, 12)); // NOI18N
        editbutton.setText("Edit");
        editbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editbuttonActionPerformed(evt);
            }
        });

        undonebutton.setFont(new java.awt.Font("Modern No. 20", 1, 14)); // NOI18N
        undonebutton.setText("Mark Undone");
        undonebutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                undonebuttonActionPerformed(evt);
            }
        });

        createburden.setFont(new java.awt.Font("Modern No. 20", 1, 14)); // NOI18N
        createburden.setText("Create Burden");
        createburden.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createburdenActionPerformed(evt);
            }
        });

        duedate.setText("yyyy-mm-dd");
        duedate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                duedateActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(undonebutton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(markdone, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(deletebutton, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(editbutton, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane4)
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(homebutton))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel8)
                                .addGap(138, 138, 138)))
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(22, 22, 22)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel4))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(priority, 0, 130, Short.MAX_VALUE)
                                    .addComponent(title, javax.swing.GroupLayout.DEFAULT_SIZE, 130, Short.MAX_VALUE)
                                    .addComponent(duedate)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addComponent(jLabel6)
                                .addGap(18, 18, 18)
                                .addComponent(category, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(createburden)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel7)
                                        .addGap(18, 18, 18)
                                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(39, 39, 39))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(homebutton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel8))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(title, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(6, 6, 6)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(duedate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(priority, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(category, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel7)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(createburden)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 36, Short.MAX_VALUE)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 245, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(undonebutton)
                    .addComponent(markdone)
                    .addComponent(deletebutton)
                    .addComponent(editbutton)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
    
    private void homebuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_homebuttonActionPerformed
         //this takes the user back to the home page with a message
        if (snarkPack != null) {
            String encourage = snarkPack.getEncouragement();
            JOptionPane.showMessageDialog(this, encourage);
        }    
        new landingPage().setVisible(true);  
        this.dispose();  
    }//GEN-LAST:event_homebuttonActionPerformed

    private void titleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_titleActionPerformed
                           if (snarkPack != null) {
                    String encourage = snarkPack.getEncouragement();
                    JOptionPane.showMessageDialog(this, encourage);
}                             
    }//GEN-LAST:event_titleActionPerformed

    private void undonebuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_undonebuttonActionPerformed
       //allows users to update tasks as undone if they change thier mind
        int row = burdentable.getSelectedRow();//gets the index of the slected row but if nothings slected its -1
        if (row == -1) {// this means if no row is slected
            javax.swing.JOptionPane.showMessageDialog(this, "Select a burden first.");
            return;
        }
                    
        Task t = taskList.get(row);//gets the task from the task list that lives in that row
        t.undoDone();//calls undo method to change status
          repo.updateTask(t);
        refreshTable();  //updates table so info is accuratly displayed
        
         if (snarkPack != null) {
                    String scold = snarkPack.getScold();
                    JOptionPane.showMessageDialog(this, scold);
         }
                      
    }//GEN-LAST:event_undonebuttonActionPerformed

    private void markdoneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_markdoneActionPerformed
               int row = burdentable.getSelectedRow();
        if (row == -1) {
            javax.swing.JOptionPane.showMessageDialog(this, "Select a burden first.");
            return;
        }
        Task t = taskList.get(row);
        t.markDone();// changes the tasks ststaus in memor 
        repo.updateTask(t); 
        
        refreshTable();
        
                
        if (snarkPack != null) {
            String praise = snarkPack.getPraise();
            JOptionPane.showMessageDialog(this, praise);
        }
    }//GEN-LAST:event_markdoneActionPerformed

    private void deletebuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deletebuttonActionPerformed
            int row = burdentable.getSelectedRow();
            if (row == -1) {
            javax.swing.JOptionPane.showMessageDialog(this, "Select a burden first.");
            return;
            }
    
            Task t = taskList.get(row);
            // deletes from the file first
            repo.deleteTask(t.getId());

            // then deletes from  the in memory list (in memeory means in ram as in the tasks only exist when this app is running and will vanish when closed cuz its not stored in a file)
            taskList.remove(row);
            refreshTable();
            
                if (snarkPack != null) {
                    String scold = snarkPack.getScold();
                    JOptionPane.showMessageDialog(this, scold);
                    }
    }//GEN-LAST:event_deletebuttonActionPerformed

    private void editbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editbuttonActionPerformed
        int row = burdentable.getSelectedRow();
            if (row == -1) {
                javax.swing.JOptionPane.showMessageDialog(this, "Select a burden first.");
                return;
            }
            Task t = taskList.get(row); //getss the users task 
            title.setText(t.getTitle());//puts all the details back into the text field so the user can edit them 
            duedate.setText(t.getDueDate());
            priority.setSelectedItem(t.getPriority().name());
            category.setSelectedItem(t.getCategory().name());// thee '.name()' is there so we get the text thats in the enums
               
            showSubtasks(t);
            
           if (snarkPack != null) {
        String praise = snarkPack.getPraise();
        JOptionPane.showMessageDialog(this, praise);
}

            editingIndex = row; //updates subtask list
    }//GEN-LAST:event_editbuttonActionPerformed

    private void createburdenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createburdenActionPerformed
        // this takesall the details the user enters into the fields and compiles them at once with the create button
        // the title
         String taskTitle = title.getText();//pulls out the title from gui so it can be used for operations in other classes
        if (taskTitle.isEmpty()) {
            javax.swing.JOptionPane.showMessageDialog(this, "Please enter a title.");
            return;
        }
        //the date
        String dueDateText = duedate.getText();
       //priority
        String prioString = (String) priority.getSelectedItem();//gets the current choice
        Priority p = Priority.valueOf(prioString);// this amkes the string an actual priority value
        //category
        String catString = (String) category.getSelectedItem();
        Category c = Category.valueOf(catString);
        //status
        Status s = Status.Uncompleted;//task always starts as uncomplete
         // get the subtask text from the text field
        String subText = subtask.getText().trim();
                        Task t; //here i declared a variable that will hold the task object once its created
 
                        //______________________
                        //EDIT TASK
                        //_________________________-/___
                   //  int editingIndex;
                        if (editingIndex >= 0) {//this is to see if their editing an existing task 
                            t = taskList.get(editingIndex);
                            t.setTitle(taskTitle);
                            t.setDueDate(dueDateText);
                            t.setPriority(p);
                            t.setCategory(c);
                            // optional: if user typed a new subtask while editing, add it
                            if (!subText.isEmpty()) {
                                // give the new subtask an id after the existing ones
                                int newSubId = t.getSubTasks().size() + 1;
                                SubTask st = new SubTask(newSubId, subText);
                                t.addSubtask(st);
                            }
                            // save changes to file
                            repo.updateTask(t);
                            // reset editing index
                            editingIndex = -1;
                        } else {
                            
                            // ________________________
                            // CREATE NEW TASK
                            // -________________________
                            t = new Task(nextId++, taskTitle, dueDateText, p, c, s);

                            // if user added a subtask on creation, attach it
                            if (!subText.isEmpty()) {
                                SubTask st = new SubTask(1, subText);
                                t.addSubtask(st);
                            }

                            // add to in-memory list
                            taskList.add(t);

                            // and save to file
                            repo.saveTask(t);
                        }
                        if (snarkPack != null) {
                        String praise = snarkPack.getPraise();
                        JOptionPane.showMessageDialog(this, praise);
}


                        // update UI after either create or edit
                        refreshTable();
                        showSubtasks(t);

                        // clear input fields
                        title.setText("");
                        duedate.setText("");
                        subtask.setText("");
                        priority.setSelectedIndex(0);
                        category.setSelectedIndex(0);

                        // if you have snark wired up, you can also do:
                        // showSnark(true);                                  
    }//GEN-LAST:event_createburdenActionPerformed

    private void duedateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_duedateActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_duedateActionPerformed

    private void burdenlistMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_burdenlistMouseClicked
                      if (snarkPack != null) {
                    String encourage = snarkPack.getEncouragement();
                    JOptionPane.showMessageDialog(this, encourage);
}
    }//GEN-LAST:event_burdenlistMouseClicked

 
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
    java.awt.EventQueue.invokeLater(() -> new stt.landingPage().setVisible(true));
}


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JList<String> burdenlist;
    private javax.swing.JTable burdentable;
    private javax.swing.JComboBox<String> category;
    private javax.swing.JButton createburden;
    private javax.swing.JButton deletebutton;
    private javax.swing.JTextField duedate;
    private javax.swing.JButton editbutton;
    private javax.swing.JButton homebutton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTable jTable1;
    private javax.swing.JButton markdone;
    private javax.swing.JComboBox<String> priority;
    private javax.swing.JTextPane subtask;
    private javax.swing.JTextField title;
    private javax.swing.JButton undonebutton;
    // End of variables declaration//GEN-END:variables

}

/*
SOURCES

https://docs.oracle.com/javase/tutorial/uiswing/components/table.html
https://docs.oracle.com/javase/8/docs/api/javax/swing/table/DefaultTableModel.html
--these helped manage my task table (clear, add, manage etc)and my list to display sub tasks(update dynamically even in edits)

https://docs.oracle.com/javase/tutorial/java/javaOO/enum.html
--this helped me take the strings from user selection like prioirty or category and get them into the actual enums

*/