package reports;

import java.io.BufferedReader;
import java.io.FileReader;
import java.io.FileWriter;
import java.util.ArrayList;
import java.util.List;
import javax.swing.table.DefaultTableModel;
import stt.landingPage;
import javax.swing.JOptionPane;
import settings.SnarkPack;
import settings.snarkUI;
import settings.ThemeManager;
import Task.Task;
import Task.Status;
import Task.storage.fileTaskRepository;
import java.time.LocalDate;
import Task.storage.fileTaskRepository;

/**
 *
 * @author Blesson Robert 
 */
public class GUI extends javax.swing.JFrame {
    private SnarkPack snarkPack;
    private fileTaskRepository repo;   // connect reports to task storage
 
    /**
     * Creates new form GUI
     */
    public GUI() {
        initComponents();
        repo = new fileTaskRepository("tasks.dat"); //pull fdetails from the exisintg task file 
        updateTable(new ArrayList<>()); 
        refreshBTNActionPerformed(null); // auto refresh/load data upon load/open

        
    // get whatever the user chose in settings
    snarkPack = snarkUI.currentSnarkPack;
    ThemeManager.applyTheme(this, snarkPack);//uses theme

        
    }
    // updates th top summary labels
    public void updateSummary(int total, int completed, int overdue) {
        totalTasksLBL.setText(String.valueOf(total));
        completedTasksLBL.setText(String.valueOf(completed));
        overdueTasksLBL.setText(String.valueOf(overdue));

    }

    // Updates the rows in the progresss table
    public void updateTable(List<Object[]> rows) {
        DefaultTableModel model = (DefaultTableModel) progressTable.getModel();
        model.setRowCount(0); // clear the old rows

        for (Object[] r : rows) {
            model.addRow(r);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSeparator1 = new javax.swing.JSeparator();
        jMenuItem1 = new javax.swing.JMenuItem();
        refreshBTN = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        quitBTN = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        totalTasksLBL = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        completedTasksLBL = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        overdueTasksLBL = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        streakLBL = new javax.swing.JLabel();
        progressScroll = new javax.swing.JScrollPane();
        progressTable = new javax.swing.JTable();
        exportBTN = new javax.swing.JButton();
        homeBTN = new javax.swing.JButton();

        jMenuItem1.setText("jMenuItem1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(204, 204, 255));

        refreshBTN.setBackground(new java.awt.Color(102, 255, 51));
        refreshBTN.setForeground(java.awt.Color.black);
        refreshBTN.setText("Refresh");
        refreshBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                refreshBTNActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Songti SC", 1, 24)); // NOI18N
        jLabel1.setText("Reports Panel (The Tomb of Wretched Deeds)");

        quitBTN.setBackground(new java.awt.Color(255, 51, 51));
        quitBTN.setText("Quit App");
        quitBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                quitBTNActionPerformed(evt);
            }
        });

        jPanel2.setBackground(new java.awt.Color(153, 204, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        jPanel2.setLayout(new java.awt.GridLayout(2, 4, 5, 5));

        jLabel2.setText("Total Tasks:");
        jPanel2.add(jLabel2);

        totalTasksLBL.setText("totalTasksLBL");
        jPanel2.add(totalTasksLBL);

        jLabel4.setText("Completed Tasks:");
        jPanel2.add(jLabel4);

        completedTasksLBL.setText("completedTasksLBL");
        jPanel2.add(completedTasksLBL);

        jLabel3.setText("Overdue Tasks:");
        jPanel2.add(jLabel3);

        overdueTasksLBL.setText("overdueTasksLBl");
        jPanel2.add(overdueTasksLBL);

        jLabel5.setText("Streak:");
        jPanel2.add(jLabel5);

        streakLBL.setText("feature coming soon");
        jPanel2.add(streakLBL);

        progressTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Task Name", "Status", "Due In (days)"
            }
        ));
        progressScroll.setViewportView(progressTable);

        exportBTN.setBackground(new java.awt.Color(102, 102, 255));
        exportBTN.setText("Export");
        exportBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exportBTNActionPerformed(evt);
            }
        });

        homeBTN.setText("Home");
        homeBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                homeBTNActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(72, 72, 72)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 532, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(progressScroll, javax.swing.GroupLayout.PREFERRED_SIZE, 497, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(refreshBTN, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(exportBTN, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(quitBTN, javax.swing.GroupLayout.Alignment.TRAILING))
                            .addComponent(homeBTN, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(56, 56, 56)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 8, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(progressScroll, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(12, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(refreshBTN)
                        .addGap(18, 18, 18)
                        .addComponent(exportBTN)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(homeBTN)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(quitBTN)
                        .addGap(15, 15, 15))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void refreshBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_refreshBTNActionPerformed
        
        java.util.List<ReportTask> tasks = new java.util.ArrayList<>();

        try {
            java.util.ArrayList<Task> realTasks = repo.findAll();

            for (Task t : realTasks) {

                // title from Task
                String name = t.getTitle();

                // work out status string for report
                String stat;
                if (t.getStatus() == Status.Completed) {
                    stat = "Completed";
                } else {
                    // check overdue using dueDate
                    String dd = t.getDueDate();
                    String tmp = "Active";

                    if (dd != null && !dd.trim().equals("")) {
                        try {
                            LocalDate due = LocalDate.parse(dd.trim()); // yyyy-mm-dd
                            LocalDate today = LocalDate.now();
                            if (due.isBefore(today)) {
                                tmp = "Overdue";
                            }
                        } catch (Exception ex) {
                            // bad date, just leave as Active
                        }
                    }

                    stat = tmp;
                }

                // calc days until due (rough)
                int day = 0;
                String dd2 = t.getDueDate();
                if (dd2 != null && !dd2.trim().equals("")) {
                    try {
                        LocalDate due = LocalDate.parse(dd2.trim());
                        LocalDate today = LocalDate.now();
                        long diff = due.toEpochDay() - today.toEpochDay();
                        day = (int) diff;
                    } catch (Exception ex) {
                        day = 0;
                    }
                }

                tasks.add(new ReportTask(name, stat, day));
            }
        } catch (Exception e) {
            // repo failed or something, we just fall back below
        }

        // if repo empty or weird we jus add some default ones
        if (tasks.size() < 2) { 
            tasks.add(new ReportTask("Write OOP Reprot", "Completed", 1));
            tasks.add(new ReportTask("Do Dishes", "Overude", -1));
            tasks.add(new ReportTask("Studdy for Exam", "Active", 0));
        }

        // get stats frm tasks
        ReportStats stats = ReportStats.fromTasks(tasks);

        updateSummary(
            stats.getTotalTasks(),
            stats.getCompletedTasks(),
            stats.getOverdueTasks()
        );

        // put tasks into the table rows
        java.util.List<Object[]> rows = new java.util.ArrayList<>();
        for (ReportTask t : tasks) {
            rows.add(new Object[] {
                t.getName(),
                t.getStatus(),
                t.getDueInDays()
            });
        }

        updateTable(rows);
        
        if (snarkPack != null) {
            String praise = snarkPack.getPraise();
            JOptionPane.showMessageDialog(this, praise);
        }

    }//GEN-LAST:event_refreshBTNActionPerformed

    private void quitBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_quitBTNActionPerformed
                     if (snarkPack != null) {
                    String scold = snarkPack.getScold();
                    JOptionPane.showMessageDialog(this, scold);
                    }
        System.exit(0);
    }//GEN-LAST:event_quitBTNActionPerformed

    private void exportBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exportBTNActionPerformed
        FileWriter fw;
        try {
            fw = new FileWriter("report.txt");

            // Write summary text
            fw.write("Total Tasks: " + totalTasksLBL.getText() + "\n");
            fw.write("Completed Tasks: " + completedTasksLBL.getText() + "\n");
            fw.write("Overdue Tasks: " + overdueTasksLBL.getText() + "\n");

            // Write table rows
            DefaultTableModel model = (DefaultTableModel) progressTable.getModel();
            for (int i = 0; i < model.getRowCount(); i++) {
                fw.write(model.getValueAt(i, 0) + " | "
                        + model.getValueAt(i, 1) + " | "
                        + model.getValueAt(i, 2) + "\n");
            }

            fw.close();
            JOptionPane.showMessageDialog(this, "Report saved!");

        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Something went wrong when exporting.");
        }
        
                if (snarkPack != null) {
            String praise = snarkPack.getPraise();
            JOptionPane.showMessageDialog(this, praise);
                }
    }//GEN-LAST:event_exportBTNActionPerformed

    private void homeBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_homeBTNActionPerformed
         //this takes the user back to the home page with a message
        if (snarkPack != null) {
            String encourage = snarkPack.getEncouragement();
            JOptionPane.showMessageDialog(this, encourage);
        }    
        new landingPage().setVisible(true);  
        this.dispose();  
    }//GEN-LAST:event_homeBTNActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel completedTasksLBL;
    private javax.swing.JButton exportBTN;
    private javax.swing.JButton homeBTN;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel overdueTasksLBL;
    private javax.swing.JScrollPane progressScroll;
    private javax.swing.JTable progressTable;
    private javax.swing.JButton quitBTN;
    private javax.swing.JButton refreshBTN;
    private javax.swing.JLabel streakLBL;
    private javax.swing.JLabel totalTasksLBL;
    // End of variables declaration//GEN-END:variables

 
}