/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package settings;
import javax.swing.JOptionPane;
import stt.landingPage;

/*
 * classname: snarkUI.java

 * @amelia maxwell
 * x23471092
 */

public class snarkUI extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(snarkUI.class.getName());

    public static SnarkPack currentSnarkPack;   
      private SnarkPack snarkPack;//this hold whatever user picks
      
                                   
    public snarkUI() {
            initComponents();
            
          try {                                         //without this try catch settings could only open once.
              initSnarkOptions();   /// the second time youd try to open it in one run it would crash and refuse to open.
          } catch (Exception e) {   /// i think its because the first time it runs no stored values can cause a crash
               e.printStackTrace();///  then the second time we have stored values that would cause a crash as it tried to load old values into components that were null in snark                 
          }                                                  //this try catch stops it from crahsing our constructor so this frame can run even if,   ///initSnarkOptions() gets an error
    }                                                       



    
        // Set up the actual snark levels/styles instead of "Item 1"
    private void initSnarkOptions() {//this sets up the snark levels and styles so it not eg item1
        snarkLevel.setModel(new javax.swing.DefaultComboBoxModel<>(//adds options to combo box
                new String[]
                    {"Off", "Mild", "Medium", "Spicy"}));

        SnarkStyle.setModel(new javax.swing.DefaultComboBoxModel<>(
                new String[]
                    {"Pirate", "Shakespearean", "Wizard"}));

        preveiw.setEditable(false);//stops user from typing into the preveiw box
        
        themeChoice.setModel(new javax.swing.DefaultComboBoxModel<>(
                new String[]
                    { "Light", "Dark", "Ludicrous" }));
            themeChoice.setSelectedItem("Light");//sensible default theme
}
    

    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jComboBox2 = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        snarkLevel = new javax.swing.JComboBox<>();
        SnarkStyle = new javax.swing.JComboBox<>();
        username = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        preveiw = new javax.swing.JTextArea();
        saveButton = new javax.swing.JButton();
        homeButton = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        themeChoice = new javax.swing.JComboBox<>();

        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel6.setText("jLabel6");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Old English Text MT", 2, 24)); // NOI18N
        jLabel1.setText("The Grimoire of Configurations");

        jLabel2.setFont(new java.awt.Font("Palatino Linotype", 2, 14)); // NOI18N
        jLabel2.setText("Choose a Snark Level:");

        jLabel3.setFont(new java.awt.Font("Palatino Linotype", 2, 14)); // NOI18N
        jLabel3.setText("Choose a Snark style:");

        jLabel4.setFont(new java.awt.Font("Palatino Linotype", 2, 14)); // NOI18N
        jLabel4.setText("Enter  Your User Name:");

        jLabel5.setFont(new java.awt.Font("Palatino Linotype", 2, 14)); // NOI18N
        jLabel5.setText("Preview Your Snark Settings:");

        snarkLevel.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        SnarkStyle.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        username.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                usernameActionPerformed(evt);
            }
        });

        preveiw.setColumns(20);
        preveiw.setFont(new java.awt.Font("Palatino Linotype", 2, 12)); // NOI18N
        preveiw.setRows(5);
        jScrollPane1.setViewportView(preveiw);

        saveButton.setFont(new java.awt.Font("Onyx", 0, 18)); // NOI18N
        saveButton.setText("SAVE ");
        saveButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveButtonActionPerformed(evt);
            }
        });

        homeButton.setFont(new java.awt.Font("Onyx", 0, 18)); // NOI18N
        homeButton.setText("RETURN HOME");
        homeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                homeButtonActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Palatino Linotype", 2, 12)); // NOI18N
        jLabel7.setText("(Snark Settings)");

        jLabel8.setFont(new java.awt.Font("Palatino Linotype", 2, 14)); // NOI18N
        jLabel8.setText("Colour Theme:");

        themeChoice.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        themeChoice.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                themeChoiceActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 324, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel7)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(14, 14, 14)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel4)
                                        .addGap(0, 0, Short.MAX_VALUE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel3)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(saveButton, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(username)
                                            .addComponent(SnarkStyle, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(18, 18, 18)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(jLabel2)
                                            .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(homeButton)
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                .addComponent(themeChoice, 0, 100, Short.MAX_VALUE)
                                                .addComponent(snarkLevel, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(homeButton))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(themeChoice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addComponent(username, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel2)
                    .addComponent(snarkLevel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(SnarkStyle, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 38, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(saveButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel7))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void homeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_homeButtonActionPerformed
         //this takes the user back to the home page with a message
        if (snarkPack != null) {
            String encourage = snarkPack.getEncouragement();
            JOptionPane.showMessageDialog(this, encourage);
        }    
        new landingPage().setVisible(true);  
        this.dispose();  
    }//GEN-LAST:event_homeButtonActionPerformed

    
   
    private void saveButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveButtonActionPerformed
               // SAVE BUTTON  gets values and builds custom snarkpack  and shows a preview

        String name = username.getText();
        if (name.isEmpty()) {
            javax.swing.JOptionPane.showMessageDialog(this, "Please enter thy user name.");
            return;
        }

            String level = (String) snarkLevel.getSelectedItem();//connects snark packs
            String style = (String) SnarkStyle.getSelectedItem();
           String theme = (String) themeChoice.getSelectedItem();

                  snarkPack = new SnarkPack(style, level, name, theme);//builds personalised snarkpack
                  snarkUI.currentSnarkPack = snarkPack;//remembers it for whole project 
                  
                  StringBuilder sb = new StringBuilder();// for preveiw box
                      sb.append("Praise:\n");//for prevwieing snark settings
                      sb.append(snarkPack.getPraise()).append("\n\n");
                      sb.append("Scold:\n");
                      sb.append(snarkPack.getScold()).append("\n\n");
                  preveiw.setText(sb.toString());//sends text to preveiw area
                
                  //success message
                  javax.swing.JOptionPane.showMessageDialog(this, "thy snark configurations saved to scroll (settings saved).");
                
                
                
    }//GEN-LAST:event_saveButtonActionPerformed

    private void usernameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_usernameActionPerformed
        // handled in save button
    }//GEN-LAST:event_usernameActionPerformed

    private void themeChoiceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_themeChoiceActionPerformed
       // updates the snark pack with the new theme
        if (currentSnarkPack != null) {
              String theme = (String) themeChoice.getSelectedItem();   // get s the theme the user picked from combo box
            currentSnarkPack.setTheme(theme);
        }
    }//GEN-LAST:event_themeChoiceActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new snarkUI().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> SnarkStyle;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.JButton homeButton;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea preveiw;
    private javax.swing.JButton saveButton;
    private javax.swing.JComboBox<String> snarkLevel;
    private javax.swing.JComboBox<String> themeChoice;
    private javax.swing.JTextField username;
    // End of variables declaration//GEN-END:variables
}
